// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: forward_transport.proto

package forwardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Forwarding_Propose_FullMethodName = "/forwardpb.Forwarding/Propose"
)

// ForwardingClient is the client API for Forwarding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Forwarding is the reference transport for write forwarding: it ships opaque
// byte blobs from a follower to the leader. It runs on every node; only the
// current leader accepts work through it. The payload bytes are owned by the
// caller, not by this transport.
type ForwardingClient interface {
	Propose(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Envelope, error)
}

type forwardingClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardingClient(cc grpc.ClientConnInterface) ForwardingClient {
	return &forwardingClient{cc}
}

func (c *forwardingClient) Propose(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, Forwarding_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardingServer is the server API for Forwarding service.
// All implementations must embed UnimplementedForwardingServer
// for forward compatibility.
//
// Forwarding is the reference transport for write forwarding: it ships opaque
// byte blobs from a follower to the leader. It runs on every node; only the
// current leader accepts work through it. The payload bytes are owned by the
// caller, not by this transport.
type ForwardingServer interface {
	Propose(context.Context, *Envelope) (*Envelope, error)
	mustEmbedUnimplementedForwardingServer()
}

// UnimplementedForwardingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwardingServer struct{}

func (UnimplementedForwardingServer) Propose(context.Context, *Envelope) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedForwardingServer) mustEmbedUnimplementedForwardingServer() {}
func (UnimplementedForwardingServer) testEmbeddedByValue()                    {}

// UnsafeForwardingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardingServer will
// result in compilation errors.
type UnsafeForwardingServer interface {
	mustEmbedUnimplementedForwardingServer()
}

func RegisterForwardingServer(s grpc.ServiceRegistrar, srv ForwardingServer) {
	// If the following call panics, it indicates UnimplementedForwardingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Forwarding_ServiceDesc, srv)
}

func _Forwarding_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardingServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forwarding_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardingServer).Propose(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

// Forwarding_ServiceDesc is the grpc.ServiceDesc for Forwarding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Forwarding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forwardpb.Forwarding",
	HandlerType: (*ForwardingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _Forwarding_Propose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forward_transport.proto",
}
