// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forward_transport.proto

package forwardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_forward_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_forward_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_forward_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_forward_transport_proto protoreflect.FileDescriptor

const file_forward_transport_proto_rawDesc = "" +
	"\n" +
	"\x17forward_transport.proto\x12\tforwardpb\"$\n" +
	"\bEnvelope\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload2A\n" +
	"\n" +
	"Forwarding\x123\n" +
	"\aPropose\x12\x13.forwardpb.Envelope\x1a\x13.forwardpb.EnvelopeBCZAgithub.com/fuchstim/literaft/cmd/literaft/forward/proto;forwardpbb\x06proto3"

var (
	file_forward_transport_proto_rawDescOnce sync.Once
	file_forward_transport_proto_rawDescData []byte
)

func file_forward_transport_proto_rawDescGZIP() []byte {
	file_forward_transport_proto_rawDescOnce.Do(func() {
		file_forward_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forward_transport_proto_rawDesc), len(file_forward_transport_proto_rawDesc)))
	})
	return file_forward_transport_proto_rawDescData
}

var file_forward_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_forward_transport_proto_goTypes = []any{
	(*Envelope)(nil), // 0: forwardpb.Envelope
}
var file_forward_transport_proto_depIdxs = []int32{
	0, // 0: forwardpb.Forwarding.Propose:input_type -> forwardpb.Envelope
	0, // 1: forwardpb.Forwarding.Propose:output_type -> forwardpb.Envelope
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forward_transport_proto_init() }
func file_forward_transport_proto_init() {
	if File_forward_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forward_transport_proto_rawDesc), len(file_forward_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forward_transport_proto_goTypes,
		DependencyIndexes: file_forward_transport_proto_depIdxs,
		MessageInfos:      file_forward_transport_proto_msgTypes,
	}.Build()
	File_forward_transport_proto = out.File
	file_forward_transport_proto_goTypes = nil
	file_forward_transport_proto_depIdxs = nil
}
