package vfs_test

import (
	"errors"
	"path/filepath"
	"sync"
	"time"

	"github.com/hashicorp/go-hclog"
	"github.com/ncruces/go-sqlite3"
	sqlite3vfs "github.com/ncruces/go-sqlite3/vfs"

	"github.com/fuchstim/literaft/internal/vfs"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// Register's pageSize is used unconditionally for frame-offset math, not
// just to optionally enforce a page-size mismatch -- passing 0 doesn't
// disable a check, it silently corrupts frame parsing for every WAL write
// afterward. Register must refuse it outright.
var _ = Describe("Register", func() {
	It("panics if pageSize is 0", func() {
		Expect(func() {
			vfs.Register("literaft-vfs-test-zero-pagesize", sqlite3vfs.Find(""), alwaysCommitGate{}, 0, hclog.NewNullLogger())
		}).To(Panic())
	})
})

// SQLite prefers OpenFilename over Open once a VFS implements both, so
// every other test in this package -- opened via sqlite3.Open's URI DSNs --
// exercises VFS.OpenFilename, never VFS.Open itself. This calls the
// registered VFS's Open directly to cover that path, using an empty name
// (temp file), the only call shape the base VFS supports there.
var _ = Describe("VFS.Open (the non-Filename path)", func() {
	It("wraps a directly-opened temp file, and the wrapped file behaves like a plain file", func() {
		v := sqlite3vfs.Find(vfsName)

		f, _, err := v.Open("", sqlite3vfs.OPEN_TEMP_JOURNAL|sqlite3vfs.OPEN_CREATE|
			sqlite3vfs.OPEN_READWRITE|sqlite3vfs.OPEN_DELETEONCLOSE)
		Expect(err).NotTo(HaveOccurred())
		defer f.Close()

		data := []byte("hello from a directly-opened file")
		n, err := f.WriteAt(data, 0)
		Expect(err).NotTo(HaveOccurred())
		Expect(n).To(Equal(len(data)))

		got := make([]byte, len(data))
		n, err = f.ReadAt(got, 0)
		Expect(err).NotTo(HaveOccurred())
		Expect(n).To(Equal(len(data)))
		Expect(got).To(Equal(data))
	})
})

// Byte-identical WAL/db files aren't achievable across runs (WAL salts are
// randomly generated by SQLite itself), so this checks the observable,
// logical no-behavior-change claim instead: identical DDL/DML through the
// wrapper VFS and through the stock default VFS must produce the same
// journal mode, row content, page count, and a clean integrity check.
var _ = Describe("wrapper VFS transparency", func() {
	It("produces logically identical results to the default VFS", func() {
		const ddl = `
			CREATE TABLE t (id INTEGER PRIMARY KEY, v TEXT);
			INSERT INTO t (v) VALUES ('a'), ('b'), ('c');
		`
		dir := GinkgoT().TempDir()

		wrapped, err := sqlite3.Open("file:" + filepath.Join(dir, "wrapped.db") + "?vfs=" + vfsName)
		Expect(err).NotTo(HaveOccurred())
		defer wrapped.Close()

		plain, err := sqlite3.Open("file:" + filepath.Join(dir, "plain.db"))
		Expect(err).NotTo(HaveOccurred())
		defer plain.Close()

		for _, c := range []*sqlite3.Conn{wrapped, plain} {
			Expect(c.Exec("PRAGMA journal_mode=WAL")).To(Succeed())
			Expect(c.Exec("PRAGMA synchronous=NORMAL")).To(Succeed())
			Expect(c.Exec(ddl)).To(Succeed())
		}

		wantMode := queryText(plain, "PRAGMA journal_mode")
		Expect(wantMode).To(Equal("wal"))
		Expect(queryText(wrapped, "PRAGMA journal_mode")).To(Equal(wantMode))

		Expect(queryInt(wrapped, "SELECT count(*) FROM t")).To(Equal(queryInt(plain, "SELECT count(*) FROM t")))
		Expect(queryInt(wrapped, "PRAGMA page_count")).To(Equal(queryInt(plain, "PRAGMA page_count")))
		Expect(queryText(wrapped, "PRAGMA integrity_check")).To(Equal("ok"))
	})
})

// Requirement #2: multiple read-write connections from the same process,
// opened through the wrapper VFS, must retain stock WAL concurrency
// (single writer, concurrent readers).
var _ = Describe("multiple read-write connections", func() {
	It("keeps readers from observing an uncommitted write, and blocks a second writer", func() {
		path := filepath.Join(GinkgoT().TempDir(), "concurrent.db")

		writer := open(path)
		Expect(writer.Exec("CREATE TABLE t (id INTEGER PRIMARY KEY, v INTEGER)")).To(Succeed())
		Expect(writer.Exec("INSERT INTO t (v) VALUES (1)")).To(Succeed())

		reader := open(path)

		Expect(writer.Exec("BEGIN IMMEDIATE")).To(Succeed())
		Expect(writer.Exec("INSERT INTO t (v) VALUES (2)")).To(Succeed())

		Expect(queryInt(reader, "SELECT count(*) FROM t")).To(Equal(int64(1)),
			"reader must not see the writer's uncommitted insert")

		second := open(path)
		second.BusyTimeout(0)
		err := second.Exec("BEGIN IMMEDIATE")
		Expect(errors.Is(err, sqlite3.BUSY)).To(BeTrue(),
			"a second writer must be denied the write lock while the first txn is open, got: %v", err)
		second.Exec("ROLLBACK")

		Expect(writer.Exec("COMMIT")).To(Succeed())

		Expect(queryInt(reader, "SELECT count(*) FROM t")).To(Equal(int64(2)))
	})

	It("serializes concurrent writers on separate connections without lost updates", func() {
		path := filepath.Join(GinkgoT().TempDir(), "writers.db")

		setup := open(path)
		Expect(setup.Exec("CREATE TABLE counter (id INTEGER PRIMARY KEY, v INTEGER)")).To(Succeed())
		Expect(setup.Exec("INSERT INTO counter (id, v) VALUES (1, 0)")).To(Succeed())

		const goroutines = 8
		const incrementsEach = 25

		var wg sync.WaitGroup
		errs := make(chan error, goroutines)
		for range goroutines {
			wg.Add(1)
			go func() {
				defer wg.Done()
				c, err := sqlite3.Open("file:" + path + "?vfs=" + vfsName)
				if err != nil {
					errs <- err
					return
				}
				defer c.Close()
				c.BusyTimeout(5 * time.Second)
				if err := c.Exec("PRAGMA journal_mode=WAL"); err != nil {
					errs <- err
					return
				}
				for range incrementsEach {
					if err := c.Exec("UPDATE counter SET v = v + 1 WHERE id = 1"); err != nil {
						errs <- err
						return
					}
				}
			}()
		}
		wg.Wait()
		close(errs)
		for err := range errs {
			Expect(err).NotTo(HaveOccurred())
		}

		verify := open(path)
		Expect(queryInt(verify, "SELECT v FROM counter WHERE id = 1")).To(Equal(int64(goroutines * incrementsEach)))
	})
})
