// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: leaderrequest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderResponse_Status int32

const (
	LeaderResponse_STATUS_UNSPECIFIED LeaderResponse_Status = 0
	LeaderResponse_STATUS_OK          LeaderResponse_Status = 1
	LeaderResponse_STATUS_NOT_LEADER  LeaderResponse_Status = 2
	LeaderResponse_STATUS_STALE_BASE  LeaderResponse_Status = 3
	LeaderResponse_STATUS_CATCHING_UP LeaderResponse_Status = 4
	LeaderResponse_STATUS_BUSY        LeaderResponse_Status = 5
	LeaderResponse_STATUS_AMBIGUOUS   LeaderResponse_Status = 6
	LeaderResponse_STATUS_INVALID     LeaderResponse_Status = 7
)

// Enum value maps for LeaderResponse_Status.
var (
	LeaderResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_NOT_LEADER",
		3: "STATUS_STALE_BASE",
		4: "STATUS_CATCHING_UP",
		5: "STATUS_BUSY",
		6: "STATUS_AMBIGUOUS",
		7: "STATUS_INVALID",
	}
	LeaderResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_NOT_LEADER":  2,
		"STATUS_STALE_BASE":  3,
		"STATUS_CATCHING_UP": 4,
		"STATUS_BUSY":        5,
		"STATUS_AMBIGUOUS":   6,
		"STATUS_INVALID":     7,
	}
)

func (x LeaderResponse_Status) Enum() *LeaderResponse_Status {
	p := new(LeaderResponse_Status)
	*p = x
	return p
}

func (x LeaderResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaderResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_leaderrequest_proto_enumTypes[0].Descriptor()
}

func (LeaderResponse_Status) Type() protoreflect.EnumType {
	return &file_leaderrequest_proto_enumTypes[0]
}

func (x LeaderResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaderResponse_Status.Descriptor instead.
func (LeaderResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_leaderrequest_proto_rawDescGZIP(), []int{1, 0}
}

type LeaderRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *LeaderRequest_Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LeaderRequest_LogEntry
	Payload       isLeaderRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderRequest) Reset() {
	*x = LeaderRequest{}
	mi := &file_leaderrequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderRequest) ProtoMessage() {}

func (x *LeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderrequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderRequest.ProtoReflect.Descriptor instead.
func (*LeaderRequest) Descriptor() ([]byte, []int) {
	return file_leaderrequest_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderRequest) GetHeader() *LeaderRequest_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LeaderRequest) GetPayload() isLeaderRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LeaderRequest) GetLogEntry() *LogEntry {
	if x != nil {
		if x, ok := x.Payload.(*LeaderRequest_LogEntry); ok {
			return x.LogEntry
		}
	}
	return nil
}

type isLeaderRequest_Payload interface {
	isLeaderRequest_Payload()
}

type LeaderRequest_LogEntry struct {
	LogEntry *LogEntry `protobuf:"bytes,2,opt,name=log_entry,json=logEntry,proto3,oneof"`
}

func (*LeaderRequest_LogEntry) isLeaderRequest_Payload() {}

type LeaderResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           LeaderResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=proto.LeaderResponse_Status" json:"status,omitempty"`
	LeaderAddr       string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	LastAppliedIndex uint64                 `protobuf:"varint,3,opt,name=last_applied_index,json=lastAppliedIndex,proto3" json:"last_applied_index,omitempty"`
	Detail           string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeaderResponse) Reset() {
	*x = LeaderResponse{}
	mi := &file_leaderrequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderResponse) ProtoMessage() {}

func (x *LeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderrequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderResponse.ProtoReflect.Descriptor instead.
func (*LeaderResponse) Descriptor() ([]byte, []int) {
	return file_leaderrequest_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderResponse) GetStatus() LeaderResponse_Status {
	if x != nil {
		return x.Status
	}
	return LeaderResponse_STATUS_UNSPECIFIED
}

func (x *LeaderResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *LeaderResponse) GetLastAppliedIndex() uint64 {
	if x != nil {
		return x.LastAppliedIndex
	}
	return 0
}

func (x *LeaderResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type LeaderRequest_Header struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // per-request unique token
	LastAppliedIndex uint64                 `protobuf:"varint,2,opt,name=last_applied_index,json=lastAppliedIndex,proto3" json:"last_applied_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeaderRequest_Header) Reset() {
	*x = LeaderRequest_Header{}
	mi := &file_leaderrequest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderRequest_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderRequest_Header) ProtoMessage() {}

func (x *LeaderRequest_Header) ProtoReflect() protoreflect.Message {
	mi := &file_leaderrequest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderRequest_Header.ProtoReflect.Descriptor instead.
func (*LeaderRequest_Header) Descriptor() ([]byte, []int) {
	return file_leaderrequest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LeaderRequest_Header) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LeaderRequest_Header) GetLastAppliedIndex() uint64 {
	if x != nil {
		return x.LastAppliedIndex
	}
	return 0
}

var File_leaderrequest_proto protoreflect.FileDescriptor

const file_leaderrequest_proto_rawDesc = "" +
	"\n" +
	"\x13leaderrequest.proto\x12\x05proto\x1a\x0elogentry.proto\"\xc7\x01\n" +
	"\rLeaderRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.proto.LeaderRequest.HeaderR\x06header\x12.\n" +
	"\tlog_entry\x18\x02 \x01(\v2\x0f.proto.LogEntryH\x00R\blogEntry\x1aF\n" +
	"\x06Header\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12last_applied_index\x18\x02 \x01(\x04R\x10lastAppliedIndexB\t\n" +
	"\apayload\"\xe0\x02\n" +
	"\x0eLeaderResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.proto.LeaderResponse.StatusR\x06status\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\x12,\n" +
	"\x12last_applied_index\x18\x03 \x01(\x04R\x10lastAppliedIndex\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\xb0\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x15\n" +
	"\x11STATUS_NOT_LEADER\x10\x02\x12\x15\n" +
	"\x11STATUS_STALE_BASE\x10\x03\x12\x16\n" +
	"\x12STATUS_CATCHING_UP\x10\x04\x12\x0f\n" +
	"\vSTATUS_BUSY\x10\x05\x12\x14\n" +
	"\x10STATUS_AMBIGUOUS\x10\x06\x12\x12\n" +
	"\x0eSTATUS_INVALID\x10\aB*Z(github.com/fuchstim/literaft/proto;protob\x06proto3"

var (
	file_leaderrequest_proto_rawDescOnce sync.Once
	file_leaderrequest_proto_rawDescData []byte
)

func file_leaderrequest_proto_rawDescGZIP() []byte {
	file_leaderrequest_proto_rawDescOnce.Do(func() {
		file_leaderrequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderrequest_proto_rawDesc), len(file_leaderrequest_proto_rawDesc)))
	})
	return file_leaderrequest_proto_rawDescData
}

var file_leaderrequest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_leaderrequest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_leaderrequest_proto_goTypes = []any{
	(LeaderResponse_Status)(0),   // 0: proto.LeaderResponse.Status
	(*LeaderRequest)(nil),        // 1: proto.LeaderRequest
	(*LeaderResponse)(nil),       // 2: proto.LeaderResponse
	(*LeaderRequest_Header)(nil), // 3: proto.LeaderRequest.Header
	(*LogEntry)(nil),             // 4: proto.LogEntry
}
var file_leaderrequest_proto_depIdxs = []int32{
	3, // 0: proto.LeaderRequest.header:type_name -> proto.LeaderRequest.Header
	4, // 1: proto.LeaderRequest.log_entry:type_name -> proto.LogEntry
	0, // 2: proto.LeaderResponse.status:type_name -> proto.LeaderResponse.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_leaderrequest_proto_init() }
func file_leaderrequest_proto_init() {
	if File_leaderrequest_proto != nil {
		return
	}
	file_logentry_proto_init()
	file_leaderrequest_proto_msgTypes[0].OneofWrappers = []any{
		(*LeaderRequest_LogEntry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderrequest_proto_rawDesc), len(file_leaderrequest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_leaderrequest_proto_goTypes,
		DependencyIndexes: file_leaderrequest_proto_depIdxs,
		EnumInfos:         file_leaderrequest_proto_enumTypes,
		MessageInfos:      file_leaderrequest_proto_msgTypes,
	}.Build()
	File_leaderrequest_proto = out.File
	file_leaderrequest_proto_goTypes = nil
	file_leaderrequest_proto_depIdxs = nil
}
