// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forward.proto

package raftproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardResponse_Status int32

const (
	ForwardResponse_STATUS_UNSPECIFIED ForwardResponse_Status = 0
	ForwardResponse_STATUS_OK          ForwardResponse_Status = 1
	ForwardResponse_STATUS_NOT_LEADER  ForwardResponse_Status = 2
	ForwardResponse_STATUS_STALE_BASE  ForwardResponse_Status = 3
	ForwardResponse_STATUS_CATCHING_UP ForwardResponse_Status = 4
	ForwardResponse_STATUS_BUSY        ForwardResponse_Status = 5
	ForwardResponse_STATUS_AMBIGUOUS   ForwardResponse_Status = 6
	ForwardResponse_STATUS_INVALID     ForwardResponse_Status = 7
)

// Enum value maps for ForwardResponse_Status.
var (
	ForwardResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_NOT_LEADER",
		3: "STATUS_STALE_BASE",
		4: "STATUS_CATCHING_UP",
		5: "STATUS_BUSY",
		6: "STATUS_AMBIGUOUS",
		7: "STATUS_INVALID",
	}
	ForwardResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_NOT_LEADER":  2,
		"STATUS_STALE_BASE":  3,
		"STATUS_CATCHING_UP": 4,
		"STATUS_BUSY":        5,
		"STATUS_AMBIGUOUS":   6,
		"STATUS_INVALID":     7,
	}
)

func (x ForwardResponse_Status) Enum() *ForwardResponse_Status {
	p := new(ForwardResponse_Status)
	*p = x
	return p
}

func (x ForwardResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_forward_proto_enumTypes[0].Descriptor()
}

func (ForwardResponse_Status) Type() protoreflect.EnumType {
	return &file_forward_proto_enumTypes[0]
}

func (x ForwardResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardResponse_Status.Descriptor instead.
func (ForwardResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{1, 0}
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ForwardRequest_Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Entry         *LogEntry              `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_forward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardRequest) GetHeader() *ForwardRequest_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ForwardRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ForwardResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           ForwardResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=raftproto.ForwardResponse_Status" json:"status,omitempty"`
	LeaderAddr       string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	LastAppliedIndex uint64                 `protobuf:"varint,3,opt,name=last_applied_index,json=lastAppliedIndex,proto3" json:"last_applied_index,omitempty"`
	Detail           string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_forward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardResponse) GetStatus() ForwardResponse_Status {
	if x != nil {
		return x.Status
	}
	return ForwardResponse_STATUS_UNSPECIFIED
}

func (x *ForwardResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *ForwardResponse) GetLastAppliedIndex() uint64 {
	if x != nil {
		return x.LastAppliedIndex
	}
	return 0
}

func (x *ForwardResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ForwardRequest_Header struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LastAppliedIndex uint64                 `protobuf:"varint,1,opt,name=last_applied_index,json=lastAppliedIndex,proto3" json:"last_applied_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForwardRequest_Header) Reset() {
	*x = ForwardRequest_Header{}
	mi := &file_forward_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest_Header) ProtoMessage() {}

func (x *ForwardRequest_Header) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest_Header.ProtoReflect.Descriptor instead.
func (*ForwardRequest_Header) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ForwardRequest_Header) GetLastAppliedIndex() uint64 {
	if x != nil {
		return x.LastAppliedIndex
	}
	return 0
}

var File_forward_proto protoreflect.FileDescriptor

const file_forward_proto_rawDesc = "" +
	"\n" +
	"\rforward.proto\x12\traftproto\x1a\x0elogentry.proto\"\xad\x01\n" +
	"\x0eForwardRequest\x128\n" +
	"\x06header\x18\x01 \x01(\v2 .raftproto.ForwardRequest.HeaderR\x06header\x12)\n" +
	"\x05entry\x18\x02 \x01(\v2\x13.raftproto.LogEntryR\x05entry\x1a6\n" +
	"\x06Header\x12,\n" +
	"\x12last_applied_index\x18\x01 \x01(\x04R\x10lastAppliedIndex\"\xe6\x02\n" +
	"\x0fForwardResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.raftproto.ForwardResponse.StatusR\x06status\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\x12,\n" +
	"\x12last_applied_index\x18\x03 \x01(\x04R\x10lastAppliedIndex\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\xb0\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x15\n" +
	"\x11STATUS_NOT_LEADER\x10\x02\x12\x15\n" +
	"\x11STATUS_STALE_BASE\x10\x03\x12\x16\n" +
	"\x12STATUS_CATCHING_UP\x10\x04\x12\x0f\n" +
	"\vSTATUS_BUSY\x10\x05\x12\x14\n" +
	"\x10STATUS_AMBIGUOUS\x10\x06\x12\x12\n" +
	"\x0eSTATUS_INVALID\x10\aB3Z1github.com/fuchstim/literaft/raft/proto;raftprotob\x06proto3"

var (
	file_forward_proto_rawDescOnce sync.Once
	file_forward_proto_rawDescData []byte
)

func file_forward_proto_rawDescGZIP() []byte {
	file_forward_proto_rawDescOnce.Do(func() {
		file_forward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forward_proto_rawDesc), len(file_forward_proto_rawDesc)))
	})
	return file_forward_proto_rawDescData
}

var file_forward_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_forward_proto_goTypes = []any{
	(ForwardResponse_Status)(0),   // 0: raftproto.ForwardResponse.Status
	(*ForwardRequest)(nil),        // 1: raftproto.ForwardRequest
	(*ForwardResponse)(nil),       // 2: raftproto.ForwardResponse
	(*ForwardRequest_Header)(nil), // 3: raftproto.ForwardRequest.Header
	(*LogEntry)(nil),              // 4: raftproto.LogEntry
}
var file_forward_proto_depIdxs = []int32{
	3, // 0: raftproto.ForwardRequest.header:type_name -> raftproto.ForwardRequest.Header
	4, // 1: raftproto.ForwardRequest.entry:type_name -> raftproto.LogEntry
	0, // 2: raftproto.ForwardResponse.status:type_name -> raftproto.ForwardResponse.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_forward_proto_init() }
func file_forward_proto_init() {
	if File_forward_proto != nil {
		return
	}
	file_logentry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forward_proto_rawDesc), len(file_forward_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forward_proto_goTypes,
		DependencyIndexes: file_forward_proto_depIdxs,
		EnumInfos:         file_forward_proto_enumTypes,
		MessageInfos:      file_forward_proto_msgTypes,
	}.Build()
	File_forward_proto = out.File
	file_forward_proto_goTypes = nil
	file_forward_proto_depIdxs = nil
}
