// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: logentry.proto

package raftproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *LogEntry_Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LogEntry_Transaction_
	Payload       isLogEntry_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_logentry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logentry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_logentry_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetHeader() *LogEntry_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LogEntry) GetPayload() isLogEntry_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LogEntry) GetTransaction() *LogEntry_Transaction {
	if x != nil {
		if x, ok := x.Payload.(*LogEntry_Transaction_); ok {
			return x.Transaction
		}
	}
	return nil
}

type isLogEntry_Payload interface {
	isLogEntry_Payload()
}

type LogEntry_Transaction_ struct {
	Transaction *LogEntry_Transaction `protobuf:"bytes,2,opt,name=transaction,proto3,oneof"`
}

func (*LogEntry_Transaction_) isLogEntry_Payload() {}

type LogEntry_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // per-proposal unique token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry_Header) Reset() {
	*x = LogEntry_Header{}
	mi := &file_logentry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry_Header) ProtoMessage() {}

func (x *LogEntry_Header) ProtoReflect() protoreflect.Message {
	mi := &file_logentry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry_Header.ProtoReflect.Descriptor instead.
func (*LogEntry_Header) Descriptor() ([]byte, []int) {
	return file_logentry_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LogEntry_Header) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogEntry_Transaction struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Pages         []*LogEntry_Transaction_Page `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	NTruncate     uint32                       `protobuf:"varint,2,opt,name=n_truncate,json=nTruncate,proto3" json:"n_truncate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry_Transaction) Reset() {
	*x = LogEntry_Transaction{}
	mi := &file_logentry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry_Transaction) ProtoMessage() {}

func (x *LogEntry_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_logentry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry_Transaction.ProtoReflect.Descriptor instead.
func (*LogEntry_Transaction) Descriptor() ([]byte, []int) {
	return file_logentry_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LogEntry_Transaction) GetPages() []*LogEntry_Transaction_Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *LogEntry_Transaction) GetNTruncate() uint32 {
	if x != nil {
		return x.NTruncate
	}
	return 0
}

type LogEntry_Transaction_Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PgNo          uint32                 `protobuf:"varint,1,opt,name=pg_no,json=pgNo,proto3" json:"pg_no,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry_Transaction_Page) Reset() {
	*x = LogEntry_Transaction_Page{}
	mi := &file_logentry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry_Transaction_Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry_Transaction_Page) ProtoMessage() {}

func (x *LogEntry_Transaction_Page) ProtoReflect() protoreflect.Message {
	mi := &file_logentry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry_Transaction_Page.ProtoReflect.Descriptor instead.
func (*LogEntry_Transaction_Page) Descriptor() ([]byte, []int) {
	return file_logentry_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *LogEntry_Transaction_Page) GetPgNo() uint32 {
	if x != nil {
		return x.PgNo
	}
	return 0
}

func (x *LogEntry_Transaction_Page) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_logentry_proto protoreflect.FileDescriptor

const file_logentry_proto_rawDesc = "" +
	"\n" +
	"\x0elogentry.proto\x12\traftproto\"\xc4\x02\n" +
	"\bLogEntry\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.raftproto.LogEntry.HeaderR\x06header\x12C\n" +
	"\vtransaction\x18\x02 \x01(\v2\x1f.raftproto.LogEntry.TransactionH\x00R\vtransaction\x1a\x18\n" +
	"\x06Header\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1a\x99\x01\n" +
	"\vTransaction\x12:\n" +
	"\x05pages\x18\x01 \x03(\v2$.raftproto.LogEntry.Transaction.PageR\x05pages\x12\x1d\n" +
	"\n" +
	"n_truncate\x18\x02 \x01(\rR\tnTruncate\x1a/\n" +
	"\x04Page\x12\x13\n" +
	"\x05pg_no\x18\x01 \x01(\rR\x04pgNo\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04dataB\t\n" +
	"\apayloadB3Z1github.com/fuchstim/literaft/raft/proto;raftprotob\x06proto3"

var (
	file_logentry_proto_rawDescOnce sync.Once
	file_logentry_proto_rawDescData []byte
)

func file_logentry_proto_rawDescGZIP() []byte {
	file_logentry_proto_rawDescOnce.Do(func() {
		file_logentry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logentry_proto_rawDesc), len(file_logentry_proto_rawDesc)))
	})
	return file_logentry_proto_rawDescData
}

var file_logentry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_logentry_proto_goTypes = []any{
	(*LogEntry)(nil),                  // 0: raftproto.LogEntry
	(*LogEntry_Header)(nil),           // 1: raftproto.LogEntry.Header
	(*LogEntry_Transaction)(nil),      // 2: raftproto.LogEntry.Transaction
	(*LogEntry_Transaction_Page)(nil), // 3: raftproto.LogEntry.Transaction.Page
}
var file_logentry_proto_depIdxs = []int32{
	1, // 0: raftproto.LogEntry.header:type_name -> raftproto.LogEntry.Header
	2, // 1: raftproto.LogEntry.transaction:type_name -> raftproto.LogEntry.Transaction
	3, // 2: raftproto.LogEntry.Transaction.pages:type_name -> raftproto.LogEntry.Transaction.Page
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logentry_proto_init() }
func file_logentry_proto_init() {
	if File_logentry_proto != nil {
		return
	}
	file_logentry_proto_msgTypes[0].OneofWrappers = []any{
		(*LogEntry_Transaction_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logentry_proto_rawDesc), len(file_logentry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logentry_proto_goTypes,
		DependencyIndexes: file_logentry_proto_depIdxs,
		MessageInfos:      file_logentry_proto_msgTypes,
	}.Build()
	File_logentry_proto = out.File
	file_logentry_proto_goTypes = nil
	file_logentry_proto_depIdxs = nil
}
