// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entry.proto

package raftproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryData is the generated wire format for Entry (see entry.go), used for
// a raft.Log's Data field. Named distinctly from Entry so the hand-written
// domain type and the generated wire type can coexist in the same package.
type EntryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Frames        []*FrameData           `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
	NTruncate     uint32                 `protobuf:"varint,3,opt,name=n_truncate,json=nTruncate,proto3" json:"n_truncate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryData) Reset() {
	*x = EntryData{}
	mi := &file_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryData) ProtoMessage() {}

func (x *EntryData) ProtoReflect() protoreflect.Message {
	mi := &file_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryData.ProtoReflect.Descriptor instead.
func (*EntryData) Descriptor() ([]byte, []int) {
	return file_entry_proto_rawDescGZIP(), []int{0}
}

func (x *EntryData) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EntryData) GetFrames() []*FrameData {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *EntryData) GetNTruncate() uint32 {
	if x != nil {
		return x.NTruncate
	}
	return 0
}

type FrameData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pgno          uint32                 `protobuf:"varint,1,opt,name=pgno,proto3" json:"pgno,omitempty"`
	Page          []byte                 `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	mi := &file_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_entry_proto_rawDescGZIP(), []int{1}
}

func (x *FrameData) GetPgno() uint32 {
	if x != nil {
		return x.Pgno
	}
	return 0
}

func (x *FrameData) GetPage() []byte {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_entry_proto protoreflect.FileDescriptor

const file_entry_proto_rawDesc = "" +
	"\n" +
	"\ventry.proto\x12\traftproto\"q\n" +
	"\tEntryData\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12,\n" +
	"\x06frames\x18\x02 \x03(\v2\x14.raftproto.FrameDataR\x06frames\x12\x1d\n" +
	"\n" +
	"n_truncate\x18\x03 \x01(\rR\tnTruncate\"3\n" +
	"\tFrameData\x12\x12\n" +
	"\x04pgno\x18\x01 \x01(\rR\x04pgno\x12\x12\n" +
	"\x04page\x18\x02 \x01(\fR\x04pageB<Z:github.com/fuchstim/literaft/internal/raft/proto;raftprotob\x06proto3"

var (
	file_entry_proto_rawDescOnce sync.Once
	file_entry_proto_rawDescData []byte
)

func file_entry_proto_rawDescGZIP() []byte {
	file_entry_proto_rawDescOnce.Do(func() {
		file_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entry_proto_rawDesc), len(file_entry_proto_rawDesc)))
	})
	return file_entry_proto_rawDescData
}

var file_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entry_proto_goTypes = []any{
	(*EntryData)(nil), // 0: raftproto.EntryData
	(*FrameData)(nil), // 1: raftproto.FrameData
}
var file_entry_proto_depIdxs = []int32{
	1, // 0: raftproto.EntryData.frames:type_name -> raftproto.FrameData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entry_proto_init() }
func file_entry_proto_init() {
	if File_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entry_proto_rawDesc), len(file_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entry_proto_goTypes,
		DependencyIndexes: file_entry_proto_depIdxs,
		MessageInfos:      file_entry_proto_msgTypes,
	}.Build()
	File_entry_proto = out.File
	file_entry_proto_goTypes = nil
	file_entry_proto_depIdxs = nil
}
