// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forward.proto

package raftproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardResponse_Status int32

const (
	ForwardResponse_OK          ForwardResponse_Status = 0
	ForwardResponse_NOT_LEADER  ForwardResponse_Status = 1 // + leader_addr hint if known
	ForwardResponse_STALE_BASE  ForwardResponse_Status = 2 // + last_applied diagnostic
	ForwardResponse_CATCHING_UP ForwardResponse_Status = 3 // leader elected but still draining (not Ready)
	ForwardResponse_BUSY        ForwardResponse_Status = 4 // couldn't acquire the write lock in time
	ForwardResponse_AMBIGUOUS   ForwardResponse_Status = 5 // proposed, outcome unknown
)

// Enum value maps for ForwardResponse_Status.
var (
	ForwardResponse_Status_name = map[int32]string{
		0: "OK",
		1: "NOT_LEADER",
		2: "STALE_BASE",
		3: "CATCHING_UP",
		4: "BUSY",
		5: "AMBIGUOUS",
	}
	ForwardResponse_Status_value = map[string]int32{
		"OK":          0,
		"NOT_LEADER":  1,
		"STALE_BASE":  2,
		"CATCHING_UP": 3,
		"BUSY":        4,
		"AMBIGUOUS":   5,
	}
)

func (x ForwardResponse_Status) Enum() *ForwardResponse_Status {
	p := new(ForwardResponse_Status)
	*p = x
	return p
}

func (x ForwardResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_forward_proto_enumTypes[0].Descriptor()
}

func (ForwardResponse_Status) Type() protoreflect.EnumType {
	return &file_forward_proto_enumTypes[0]
}

func (x ForwardResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardResponse_Status.Descriptor instead.
func (ForwardResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{1, 0}
}

// ForwardRequest carries a follower-computed write transaction to the leader
// with the base index it was computed on. entry is a marshaled Entry (not an
// embedded message) so the leader proposes the exact bytes it validated. The
// base index rides this envelope, never the replicated log.
type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         []byte                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`                           // marshaled Entry, proposed verbatim on acceptance
	BaseIndex     uint64                 `protobuf:"varint,2,opt,name=base_index,json=baseIndex,proto3" json:"base_index,omitempty"` // originating follower's applied index at proposal time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_forward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardRequest) GetEntry() []byte {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *ForwardRequest) GetBaseIndex() uint64 {
	if x != nil {
		return x.BaseIndex
	}
	return 0
}

// ForwardResponse is the leader's answer. NOT_LEADER/STALE_BASE/CATCHING_UP/
// BUSY are pre-propose (the entry did not enter the log); AMBIGUOUS means it
// was proposed but its outcome is unknown.
type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ForwardResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=raftproto.ForwardResponse_Status" json:"status,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`     // NOT_LEADER hint, if known
	LastApplied   uint64                 `protobuf:"varint,3,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"` // STALE_BASE diagnostic: the leader's own lastApplied
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`                               // human-readable diagnostic
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_forward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardResponse) GetStatus() ForwardResponse_Status {
	if x != nil {
		return x.Status
	}
	return ForwardResponse_OK
}

func (x *ForwardResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *ForwardResponse) GetLastApplied() uint64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *ForwardResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_forward_proto protoreflect.FileDescriptor

const file_forward_proto_rawDesc = "" +
	"\n" +
	"\rforward.proto\x12\traftproto\"E\n" +
	"\x0eForwardRequest\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\fR\x05entry\x12\x1d\n" +
	"\n" +
	"base_index\x18\x02 \x01(\x04R\tbaseIndex\"\x84\x02\n" +
	"\x0fForwardResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.raftproto.ForwardResponse.StatusR\x06status\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\x12!\n" +
	"\flast_applied\x18\x03 \x01(\x04R\vlastApplied\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"Z\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0e\n" +
	"\n" +
	"NOT_LEADER\x10\x01\x12\x0e\n" +
	"\n" +
	"STALE_BASE\x10\x02\x12\x0f\n" +
	"\vCATCHING_UP\x10\x03\x12\b\n" +
	"\x04BUSY\x10\x04\x12\r\n" +
	"\tAMBIGUOUS\x10\x05B<Z:github.com/fuchstim/literaft/internal/raft/proto;raftprotob\x06proto3"

var (
	file_forward_proto_rawDescOnce sync.Once
	file_forward_proto_rawDescData []byte
)

func file_forward_proto_rawDescGZIP() []byte {
	file_forward_proto_rawDescOnce.Do(func() {
		file_forward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forward_proto_rawDesc), len(file_forward_proto_rawDesc)))
	})
	return file_forward_proto_rawDescData
}

var file_forward_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forward_proto_goTypes = []any{
	(ForwardResponse_Status)(0), // 0: raftproto.ForwardResponse.Status
	(*ForwardRequest)(nil),      // 1: raftproto.ForwardRequest
	(*ForwardResponse)(nil),     // 2: raftproto.ForwardResponse
}
var file_forward_proto_depIdxs = []int32{
	0, // 0: raftproto.ForwardResponse.status:type_name -> raftproto.ForwardResponse.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forward_proto_init() }
func file_forward_proto_init() {
	if File_forward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forward_proto_rawDesc), len(file_forward_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forward_proto_goTypes,
		DependencyIndexes: file_forward_proto_depIdxs,
		EnumInfos:         file_forward_proto_enumTypes,
		MessageInfos:      file_forward_proto_msgTypes,
	}.Build()
	File_forward_proto = out.File
	file_forward_proto_goTypes = nil
	file_forward_proto_depIdxs = nil
}
