// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: membership.proto

package membershippb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Membership_AddVoter_FullMethodName    = "/membershippb.Membership/AddVoter"
	Membership_RemoveVoter_FullMethodName = "/membershippb.Membership/RemoveVoter"
)

// MembershipClient is the client API for Membership service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Membership is the cluster join/leave control plane. It runs on every node's
// gRPC server, alongside the raft transport. Any node accepts an AddVoter or
// RemoveVoter call; a node that isn't the leader forwards it, unchanged, to
// the current leader over the same RPC. A joining node therefore only needs
// the address of one existing member, not the leader's.
type MembershipClient interface {
	AddVoter(ctx context.Context, in *AddVoterRequest, opts ...grpc.CallOption) (*AddVoterResponse, error)
	RemoveVoter(ctx context.Context, in *RemoveVoterRequest, opts ...grpc.CallOption) (*RemoveVoterResponse, error)
}

type membershipClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipClient(cc grpc.ClientConnInterface) MembershipClient {
	return &membershipClient{cc}
}

func (c *membershipClient) AddVoter(ctx context.Context, in *AddVoterRequest, opts ...grpc.CallOption) (*AddVoterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVoterResponse)
	err := c.cc.Invoke(ctx, Membership_AddVoter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) RemoveVoter(ctx context.Context, in *RemoveVoterRequest, opts ...grpc.CallOption) (*RemoveVoterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveVoterResponse)
	err := c.cc.Invoke(ctx, Membership_RemoveVoter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServer is the server API for Membership service.
// All implementations must embed UnimplementedMembershipServer
// for forward compatibility.
//
// Membership is the cluster join/leave control plane. It runs on every node's
// gRPC server, alongside the raft transport. Any node accepts an AddVoter or
// RemoveVoter call; a node that isn't the leader forwards it, unchanged, to
// the current leader over the same RPC. A joining node therefore only needs
// the address of one existing member, not the leader's.
type MembershipServer interface {
	AddVoter(context.Context, *AddVoterRequest) (*AddVoterResponse, error)
	RemoveVoter(context.Context, *RemoveVoterRequest) (*RemoveVoterResponse, error)
	mustEmbedUnimplementedMembershipServer()
}

// UnimplementedMembershipServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipServer struct{}

func (UnimplementedMembershipServer) AddVoter(context.Context, *AddVoterRequest) (*AddVoterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVoter not implemented")
}
func (UnimplementedMembershipServer) RemoveVoter(context.Context, *RemoveVoterRequest) (*RemoveVoterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVoter not implemented")
}
func (UnimplementedMembershipServer) mustEmbedUnimplementedMembershipServer() {}
func (UnimplementedMembershipServer) testEmbeddedByValue()                    {}

// UnsafeMembershipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipServer will
// result in compilation errors.
type UnsafeMembershipServer interface {
	mustEmbedUnimplementedMembershipServer()
}

func RegisterMembershipServer(s grpc.ServiceRegistrar, srv MembershipServer) {
	// If the following call panics, it indicates UnimplementedMembershipServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Membership_ServiceDesc, srv)
}

func _Membership_AddVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).AddVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_AddVoter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).AddVoter(ctx, req.(*AddVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_RemoveVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).RemoveVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Membership_RemoveVoter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).RemoveVoter(ctx, req.(*RemoveVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Membership_ServiceDesc is the grpc.ServiceDesc for Membership service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Membership_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "membershippb.Membership",
	HandlerType: (*MembershipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVoter",
			Handler:    _Membership_AddVoter_Handler,
		},
		{
			MethodName: "RemoveVoter",
			Handler:    _Membership_RemoveVoter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "membership.proto",
}
